INSERT INTO T_CATEGORY (ID, NAME) VALUES (1, 'Fruits');
INSERT INTO T_CATEGORY (ID, NAME) VALUES (2, 'Flowers');
INSERT INTO T_CATEGORY (ID, NAME) VALUES (3, 'Vegetables');

INSERT INTO T_PRODUCT (ID, NAME, SKU_CODE, CATEGORY) VALUES (1, 'Rose', 'SKU001', 2);
INSERT INTO T_PRODUCT (ID, NAME, SKU_CODE, CATEGORY) VALUES (2, 'Jasmine', 'SKU002', 2);
INSERT INTO T_PRODUCT (ID, NAME, SKU_CODE, CATEGORY) VALUES (3, 'Apple', 'SKU003', 1);
INSERT INTO T_PRODUCT (ID, NAME, SKU_CODE, CATEGORY) VALUES (4, 'Banana', 'SKU004', 1);
INSERT INTO T_PRODUCT (ID, NAME, SKU_CODE, CATEGORY) VALUES (5, 'Orange', 'SKU005', 1);
INSERT INTO T_PRODUCT (ID, NAME, SKU_CODE, CATEGORY) VALUES (6, 'Tomato', 'SKU006', 3);
INSERT INTO T_PRODUCT (ID, NAME, SKU_CODE, CATEGORY) VALUES (7, 'Potato', 'SKU007', 3);
INSERT INTO T_PRODUCT (ID, NAME, SKU_CODE, CATEGORY) VALUES (8, 'Onion', 'SKU008', 3);