CREATE TABLE PUBLIC.T_COUNTRY (
	ID INTEGER NOT NULL IDENTITY,
	NAME VARCHAR(50) NOT NULL,
	ISD VARCHAR(20) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.T_LOCATION (
	ID INTEGER NOT NULL IDENTITY,
	NAME VARCHAR(50) NOT NULL,
	PIN BIGINT NOT NULL,
	CITY VARCHAR(50) NOT NULL,
	STATE VARCHAR(50) NOT NULL,
	COUNTRY INTEGER NOT NULL REFERENCES T_COUNTRY(ID),
	PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.T_CATEGORY (
	ID INTEGER NOT NULL IDENTITY,
	NAME VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.T_PRODUCT (
	ID INTEGER NOT NULL IDENTITY,
	SKU_CODE VARCHAR(50) NOT NULL,
	NAME VARCHAR(50) NOT NULL, 
	CATEGORY INTEGER NOT NULL REFERENCES T_CATEGORY(ID),
	PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.T_BANK (
	ID INTEGER NOT NULL IDENTITY, 
	NAME VARCHAR(50) NOT NULL, 
	IFSC VARCHAR(20) NOT NULL, 
	MICR VARCHAR(20) NOT NULL, 
	BRANCH VARCHAR(20) NOT NULL, 
	ADDRESS VARCHAR(500) NOT NULL, 
	CONTACT BIGINT NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.T_VENDOR (
	ID INTEGER NOT NULL IDENTITY, 
	COMPANY_NAME VARCHAR(100) NOT NULL, 
	COMPANY_ADDRESS VARCHAR(500) NOT NULL,
	COMPANY_PHONE BIGINT NOT NULL, 
	COMPANY_FAX BIGINT NOT NULL, 
	COMPANY_WEB_SITE VARCHAR(50) NOT NULL, 
	COMPANY_EMAIL VARCHAR(50) NOT NULL, 
	PERSON_NAME VARCHAR(50) NOT NULL, 
	PERSON_FAX BIGINT NOT NULL, 
	PERSON_MOBILE BIGINT NOT NULL, 
	PERSON_EMAIL VARCHAR(50) NOT NULL, 
	PERSON_DESIGNATION VARCHAR(50) NOT NULL, 
	ADDRESS_WORKS VARCHAR(500) NOT NULL, 
	TYPE_OWNERSHIP VARCHAR(50) NOT NULL, 
	COMPANY_NSIC VARCHAR(50) NOT NULL, 
	COMPANY_MSME VARCHAR(50) NOT NULL, 
	NATURE_BUSINESS VARCHAR(50) NOT NULL, 
	COMPANY_BANK INTEGER NOT NULL REFERENCES T_BANK(ID), 
	COMPANY_BANK_ACCOUNT VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE T_CUSTOMER (
	ID INTEGER NOT NULL IDENTITY, 
	COMPANY_NAME VARCHAR(100) NOT NULL, 
	COMPANY_ADDRESS VARCHAR(500) NOT NULL,
	COMPANY_PHONE BIGINT NOT NULL, 
	COMPANY_FAX BIGINT NOT NULL, 
	COMPANY_WEB_SITE VARCHAR(50) NOT NULL, 
	COMPANY_EMAIL VARCHAR(50) NOT NULL, 
	PERSON_NAME VARCHAR(50) NOT NULL, 
	PERSON_FAX BIGINT NOT NULL, 
	PERSON_MOBILE BIGINT NOT NULL, 
	PERSON_EMAIL VARCHAR(50) NOT NULL, 
	PERSON_DESIGNATION VARCHAR(50) NOT NULL, 
	ADDRESS_WORKS VARCHAR(500) NOT NULL, 
	TYPE_OWNERSHIP VARCHAR(50) NOT NULL, 
	COMPANY_NSIC VARCHAR(50) NOT NULL, 
	COMPANY_MSME VARCHAR(50) NOT NULL, 
	NATURE_BUSINESS VARCHAR(50) NOT NULL, 
	COMPANY_BANK INTEGER NOT NULL REFERENCES T_BANK(ID), 
	COMPANY_BANK_ACCOUNT VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.T_SALE_ORDER (
	ID INTEGER NOT NULL IDENTITY,
	CUSTOMER INTEGER NOT NULL REFERENCES T_CUSTOMER(ID),
	PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.T_ORDER_LINE (
	ID INTEGER NOT NULL IDENTITY,
	PRODUCT INTEGER NOT NULL REFERENCES T_PRODUCT(ID),
	QUANTITY DECIMAL NOT NULL, 
	UNIT_PRICE DECIMAL NOT NULL,
	SALE_ORDER INTEGER NOT NULL REFERENCES T_SALE_ORDER(ID),
	PRIMARY KEY (ID)
);
